### ISSUE TITLE
Provide a way to configure ignored dependencies

### ISSUE THREAD

**Issue by tonyarnold** [Nikoloutsos/explicitDependencyImportCheck#1]
My reports currently show a _lot_ of system frameworks in the list of violations:

```
Showing All Issues
👉 os is a transitive dependency
👉 Metal is a transitive dependency
👉 QuartzCore is a transitive dependency
👉 CoreText is a transitive dependency
👉 AppKit is a transitive dependency
👉 CoreGraphics is a transitive dependency

6 Transitive dependencies found for DataModel 🚨🚨🚨

Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```

It would be great to be able to define my own ignore list, or to have the tool ignore dependencies that aren't mentioned in the current package description.

**Comment by kostasniks** [comment]
I completely agree -- great suggestion, @tonyarnold!

I discovered [this resource](https://theapplewiki.com/wiki/Filesystem:/System/Library/Frameworks), which shows that there are even more system frameworks we should consider adding to the ignore list.

We could provide developers with the option to create an `ignoreTransitiveDependencies.json/yml` file at the root level for this purpose. However, do you think there’s interest beyond just ignoring system frameworks? If so, we can certainly add that support. And if you’re up for it, feel free to open a PR—would love to have your contribution! 😄

**Comment by Nikoloutsos** [comment]
I completely agree -- great suggestion, @tonyarnold!

I discovered [this resource](https://theapplewiki.com/wiki/Filesystem:/System/Library/Frameworks), which shows that there are even more system frameworks we should consider adding to the ignore list.

We could provide developers with the option to create an ignoreTransitiveDependencies.json/yml file at the root level for this purpose. However, do you think there’s interest beyond just ignoring system frameworks? If so, we can certainly add that support. And if you’re up for it, feel free to open a PR—would love to have your contribution! 😄

**Comment by tonyarnold** [comment]
I think that an initial option to exclude system frameworks would resolve the issue I have reported, however there will always be edge cases, so a configuration file for this tool is a good idea. 

If I can find some time I'm always happy to help out with OSS projects — it might be a few weeks at the moment though, so no promises 😄

**Comment by Nikoloutsos** [comment]
@tonyarnold [v1.0.1](https://github.com/Nikoloutsos/explicitDependencyImportCheck/releases/tag/1.0.1) resolves this.

**Comment by tonyarnold** [comment]
Thanks @Nikoloutsos, but it's still missing a considerable number of system frameworks. It looks like perhaps you grabbed a list of iOS specific frameworks? I'm still getting violations for AppKit, simd, Compression, os, Dispatch and a host of other system frameworks.

**Comment by Nikoloutsos** [comment]
Hi @tonyarnold, you're right—only iOS system libraries were initially ignored. I just released [version 1.0.2](https://github.com/Nikoloutsos/explicitDependencyImportCheck/releases/tag/1.0.2), which now excludes all the items you mentioned for IOS and macOS.

Interestingly, in addition to ignoring public system frameworks, my script also picked up some private Apple frameworks, such as _WorkoutKit_SwiftUI. I'm not entirely sure if we need them, but I thought it would be best to include everything for now. 😄

**Comment by tonyarnold** [comment]
I'm now seeing self-referential violations:

![CleanShot 2024-11-01 at 11 56 21@2x](https://github.com/user-attachments/assets/e9d39495-c73d-41d3-886d-a4b39991755d)

**Comment by Nikoloutsos** [comment]
@tonyarnold Out of curiosity, may you please check if you have any `import ViewHierarchyModelUISupport` inside the package source code? I am using sitrep tool under the hood to grab the imports statements. But now that I am thinking we can ignore self-referential transitive violations explicitly.

Once again thank you for the reports 😄

**Comment by tonyarnold** [comment]
> may you please check if you have any import ViewHierarchyModelUISupport inside the package source code

Not within the ViewHierarchyModelUISupport target, no. I had checked that before commenting, because I figured maybe I'd made a mistake, but it looks like it's doing this with every single target in my package.

**Comment by Nikoloutsos** [comment]
@tonyarnold First time seeing this 🤔
So the error looks like that if you expand?
> 👉 ViewHierarchyModelUISupport is a transitive dependency
> 1 Transitive dependencies found for ViewHierarchyModelUISupport 🚨🚨🚨

I will try to run on a big project I'm having to see if same behavior exists.
So when you search for `ViewHierarchyModelUISupport` you find no results right? If it finds something please share here cause maybe it's a sitrep bug.
In the meantime are you using any custom path on targets or you exclude any source code from package.swift?

EDIT:
![CleanShot 2024-11-01 at 10 54 16](https://github.com/user-attachments/assets/9b295f29-baee-419d-a6ec-f9fc4d895bb6)

No self-reference happened for big project I run it for. If issue persists for you and do not find anything I can just make it ignore self-reference.

**Comment by tonyarnold** [comment]
Okay, hang on I see what's happening. The build log is not showing the lines starting with 👉🏻. This is fine, it's working. 

Great work, thanks @Nikoloutsos!
