### ISSUE TITLE
Misclassified Errors Should Be Warnings or Configurable 🚨

### ISSUE THREAD

**Issue by Maetschl** [Nikoloutsos/explicitDependencyImportCheck#8]
## Issue Description

The library is currently misclassifying certain warnings as errors. While these cases are not critical, they are being displayed as errors, which may lead to confusion.

## Proposed Solutions

- **Reclassify as Warnings** ⚠️
Display these cases as warnings (e.g., in yellow) and allow the project to compile

- **Enforce as Errors** 🚨
Keep them as errors and ensure they appropriately block compilation when encountered.

## Future Consideration

It would be ideal if this behavior could become configurable, allowing users to choose whether these cases should be treated as errors or warnings based on their specific requirements.

**Comment by Nikoloutsos** [comment]
Hi @Maetschl 👋  thanks for reporting that
Initially, I reported them as errors without failing the build to raise awareness among developers.
However, many reached out, thinking the build was blocked, which caused confusion.

So yes, it makes sense to report transitive dependencies as warnings instead.

**Comment by Nikoloutsos** [comment]
Resolved on 1.0.5 version,
Thank you
